### ISSUE TITLE
RegistryConnector crashes for "keep-alive" messages

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-registry-domain#28]
The RegistryConnector crashes with:  
```
var prefix = url.split('://')[0];

TypeError: Cannot read property 'split' of undefined
```
when it shall handle a "keep-alive" messages as it is specified here: https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#keep-registration-alive

This is because this update-message does not contain a "url" field, which is expected as mandatory for update-messages by the connector implementation.

**Comment by nunofmn** [comment]
Even though this fix hasn't been released, the msg-node-vertx is using NPM to include this branch as a temporary fix was merged into the develop branch: https://github.com/reTHINK-project/dev-msg-node-vertx/commit/6a2a441cff8405544d010001e1beff5643570e73

I.e. this issue was solved in the same branch as issue https://github.com/reTHINK-project/dev-msg-node-vertx/issues/23 . Should we revert this fix, due to the upcoming TADHack?

**Comment by pchainho** [comment]
sorry, not clear why you want to revert the fix instead of having it in a new release

**Comment by nunofmn** [comment]
This specific fix assumes that "keep-alive" messages from the runtime are according to the spec (contain the msg.body.resource field).

But the update message in core-runtime isn't according to specs yet, it sends the whole hyperty data (as if it was a create message) and does not have the msg.body.resource field.

**Comment by pchainho** [comment]
ah I see. then we should have an issue in the runtime core (I don't think we have it)

**Comment by nunofmn** [comment]
I already created it: https://github.com/reTHINK-project/dev-runtime-core/issues/117

**Comment by sdruesedow** [comment]
since this issue was moved to dev-runtime-core we should close it here
