### ISSUE TITLE
User URL fix and update query per user email

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#53]
Currently User URL is set as `user://<email-domain>/<user-identifier>`

Example for my google email: `user://gmail.com/pchainho@gmail.com`

However, and according to specs it should be: `user://<idp-domain>/<user-identifier>`

Example for my google email: `user://google.com/pchainho@gmail.com`

I guess this change will have an impact on how users are searched by email.

**Comment by sbecot** [comment]
Not sure to understand. This shouldn't be email domain, neither idp-domain, but **service domain** no?
First an email is just a kind of identifier, so why searching specifically for domain? eg:
user://github.com/sbecot
is enough to find me on github.
Second, I have the same identifier for a Google and Yahoo account, which is my email adresse. So this would be 2 entries :
user://google.com/blabla@yahoo.fr 
user://yahoo.com/balbla@yahoo.fr 
This is cool to find me on google or yahoo, but if I use Google as an IdP, to connect on rethink.com service, the domain registry of rethink.com should register me as:
user://rethink.com/balbla@yahoo.fr
so you can call me there.
By the way, a user is searched by its _service domain_ and _service identifier_ (provided by an idp that is potentially out of this domain).
Users shouldn't be looked for by their emails but by their GUIDs, and/or domain/identifiers.
So where is the issue?

**Comment by BernardoMG** [comment]
I'm not sure if I understand the problem. What are you trying to achieve? A query by user email? I'm not sure if the Domain Registry supports it

**Comment by rjflp** [comment]
@pchainho There are no emails. Only a single string, that takes the format 'user://<idp-domain>/<user-identifier>'. We can split it into two fields (idp-domain and user-identifier, still no emails!).

Does it make sense to query by '<user-identifier>' only when the user can have the same user-identifier in different idp-domain?

I feel that we are pilling up functionality on the Domain Registry because the other components aren't integrated into the runtime yet.

I suggest that we wait for the connection between the runtime and Global Registry and Discovery Services before adding more functionality to the D.R.

**Comment by pchainho** [comment]
@rjflp the <user-identifier> (probably a better name is IDP User Identifier) can be an email. Also see the spec [here](https://github.com/reTHINK-project/specs/tree/master/datamodel/core/address#user-url-type). It should still be possible to query about Hyperties associated to a certain identifier even if you know the GUID.

@sbecot if I understood you, in general I agree with you but the last part :) The (IDP) user identifier could be the only info I have from a certain user eg email, mobile phone in my legacy contact list.

**Comment by sbecot** [comment]
right, and I was wrong for the fact that service domain is not included here because we are already in the domain registry, so you're right this is the IdP domain (which can be the same as the service domain).
This anyway raise another issue, as I can have 2 user identifier, from 2 different users that use 2 different IdPs, as Ricardo says. If so, looking for the user id only is not usefull.  But on the other hand, you don't always know the IdP used by someone. So for a usability reason the GUID has first to be used as the unique identifier. With it you can use global registry and you're saved!

**Comment by rjflp** [comment]
We are still to implement this as I have some issues with it. Namely, there is an important security risk.

Let's say I have the id user://google.com/ricardopereira@gmail.com.
An attacker comes in and uses the id user://hack.com/ricardopereira@gmail.com.
A search by my "ID" ricadopereira@gmail.com will return not only my hyperties, but also the atacker's, leading to the possibility of him diverting my calls.

**Comment by pchainho** [comment]
can't we use the GUID to prevent these problems?

**Comment by rjflp** [comment]
How? What would you do in the example I provide?

**Comment by sbecot** [comment]
We could use the GUID or the user URL (user://idp/userId). 
Looking for a user in the domain registry by its ID (not always an email), with lack of information of the IdP is not a good feature. By the way what is the use case?
The domain registry is a technical platform that should be queried accordingly to the model we promote: GUID=>IdPs/ID=>Service. If you suppress the IdP information, you have a partial user identifier. This is not exactly a security risk: this is just a wider result including the subset you need. If the query is not precise, the anwer will not be.

**Comment by ruimangas** [comment]
Implemented and merged into develop branch. This issue will be closed after the next release.

**Comment by nunofmn** [comment]
Fixed in [Release 0.9.0](https://github.com/reTHINK-project/dev-registry-domain/releases/tag/R0.9.0).
