### ISSUE TITLE
Updates to entries that don't exist should respond a 404 Not Found error

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#55]
Currently, update requests to entries that don't exist respond with 200 OK but it should reply with 404 Not Found error to let the runtime know about the missing entry in the registry. In principle this should not happen during normal operations ie the runtime registry and the domain registry should be synched. But for some reasons it can happen, notably we are experiencing this problem in dev environments when local Domain Registry is rebooted.

**Comment by ruimangas** [comment]
Since we're talking about Domain Registry reboots two possibilities exist:

1) the DR is being run with RAM

If this is the case, when the DR reboots all information is lost. Therefore, when an update message is sent, the connecter issues an HTTP PUT (creates or updates if exists) request and the DR will create the Hyperty and as a result will return a 200 ok code.

2) the DR is being run with a database

In this case if the DR reboots the information is kept on the database. So, when an update message is sent to the DR, it will update the Hyperty and return a 200 ok.

**Comment by pchainho** [comment]
It is the first case. If it doesn't exist it shouldn't create a new entry but return an error. The Update does not contain required information to create a new entry.

**Comment by ruimangas** [comment]
Since the update does not contain all the information to create a new entry, you are right, a 404 Not Found should be returned. Can you provides us some logs (messages being sent etc.) so we can find the problem?

**Comment by pchainho** [comment]
I'm testing the develop branch and it seems this issue has been solved by the domain registry server but the runtime registry is not handling it, yet: do you confirm?

**Comment by BernardoMG** [comment]
@pchainho I'm not sure. What method should handle this? And what is suppose to happen?

**Comment by pchainho** [comment]
I guess the methods used to register Hyperties and Data Objects and they should re-register a new entry with a warning log

**Comment by ruimangas** [comment]
There is a [pull  request](https://github.com/reTHINK-project/dev-registry-domain/pull/61) waiting to be merged that does not allow that entries without all the necessary fields to be created, thus preventing updates to nonexistent Hyperties.

Waiting for runtime to be updated.

**Comment by BernardoMG** [comment]
Runtime is updated to re-register a new entry when the update was not possible.

Changes are in branch `core-discovery-integration` of runtime-core.

This issue will be closed after the next release.

**Comment by nunofmn** [comment]
Fixed in [Release 0.9.0](https://github.com/reTHINK-project/dev-registry-domain/releases/tag/R0.9.0).
